apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"

helmCharts:
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    releaseName: base
    valuesFile: base-values.yaml
    version: 1.15.0-beta.0

  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    releaseName: istiod
    valuesFile: istiod-values.yaml
    version: 1.15.0-beta.0

  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    releaseName: gateway
    valuesFile: gateway-values.yaml
    version: 1.15.0-beta.0

